spring:
  datasource:
    url: jdbc:mysql://172.16.200.42:3306/betn_producer?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: dev_w
    password: devw@234
  redis:
    host: 172.16.200.42
    port: 6379
    password: 123456
  rabbitmq:
    host: 172.16.200.42
    username: dev_admin
    password: devadmin_pwd
    port: 5672
    virtual-host: wms_test