spring:
  datasource:
    url: jdbc:mysql://172.16.200.42:3306/betn_producer?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: dev_w
    password: devw@234