server:
  port: 20001

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-init-sqls: SET NAMES utf8mb4
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 20
        max-wait: -1ms
        max-active: 50
      shutdown-timeout: 100ms
  cloud:
    stream:
      bindings:
        simpleReceive:
          destination: pri.test.simple
          group: q
        simpleSend:
          destination: pri.test.simple
          contentType: text/plain
        orderReceive:
          destination: pri.test.order
          group: q
          consumer:
            maxAttempts: 1
        orderSend:
          destination: pri.test.order
          contentType: application/json
      rabbit:
        bindings:
          orderReceive:
            consumer:
              bindingRoutingKey: order
              autoBindDlq: true
              republishToDlq: true
              requeueRejected: true
          orderSend:
            producer:
              routing-key-expression: '''order'''

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
